export const LANDING_ROUTE = "/";
export const AUTH_ROUTE = "/auth";
export const SIGN_IN_ROUTE = "/auth/signIn";
export const REGISTER_ROUTE = "/auth/register";
export const DASHBOARD_ROUTE = "/dashboard";
export const SETTINGS_ROUTE ="/"
export const USERS_ROUTE = "/dashboard/users";
export const DEVICES_ROUTE = "/dashboard/devices";
export const PLANTS_ROUTE = "/dashboard/plants";
export const SCHEDULES_ROUTE = "/dashboard/schedules";
export const REQUESTS_ROUTE = "/requests";
export const REQUEST_DETAILS_ROUTE = "/requests/details/:requestId";
export const REQUEST_HISTORY_ROUTE = "/requests/history/:requestId";
export const ASSIGN_REQUEST_ROUTE = "/requests/assign/:requestId";
export const SOLUTION_ROUTE = "/requests/solve/:requestId";
export const CLIENT_DASHBOARD_ROUTE = "/client-dashboard";
export const SUPERVISOR_DASHBOARD_ROUTE = "/supervisor-dashboard";
export const OVERVIEW_ROUTE="/dashboard/overview"